name: build
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GTest
        run: sudo apt-get install libgtest-dev -y && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib

      - name: Build
        run: mkdir build && cd build && cmake .. && make

      - name: Static Analis and Linters
        run: ./linters/run.sh

      - name: Tests
        run: mkdir runtests && cd runtests && cmake .. && make && ./runTests

      - name: Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind && mkdir valgrind_tests && cd valgrind_tests && cmake .. && make && valgrind --tool=memcheck --leak-check=full ./runTests

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7

      - name: Generate coverage report
        run: pip install pytest && pip install pytest-cov && pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true